build:
  script:
    - curl -sL https://deb.nodesource.com/setup_11.x | bash -
    - apt-get install -y nodejs
    - node -v
    - npm -v
    - npm i
    - npm run build
    - npm i -g --unsafe-perm now
    - ls
    - now --token vbblGs1uB9MqvC4z1w0Q9kZ9 --npm
    - now alias